import javax.swing.JOptionPane;
public class RegisterForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegisterForm.class.getName());

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        // Constructor ke andar initComponents se pehle yeh paste karein:
        try {
            java.awt.Color lightNudeBeige = new java.awt.Color(242, 230, 218);
            java.awt.Color coffeeBrown = new java.awt.Color(54, 43, 36);
            java.awt.Color terracottaBtn = new java.awt.Color(184, 115, 81);

    // Message box ka background aur panel beige ho jayega
            javax.swing.UIManager.put("OptionPane.background", lightNudeBeige);
            javax.swing.UIManager.put("Panel.background", lightNudeBeige);

    // Text ka color coffee brown ho jayega
            javax.swing.UIManager.put("OptionPane.messageForeground", coffeeBrown);
            javax.swing.UIManager.put("OptionPane.messageFont", new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));

    // OK button terracotta aur white text me badal jayega
            javax.swing.UIManager.put("Button.background", terracottaBtn);
            javax.swing.UIManager.put("Button.foreground", java.awt.Color.WHITE);
            javax.swing.UIManager.put("Button.font", new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
            javax.swing.UIManager.put("Button.focusPainted", false);
        } catch (Exception e) {
            e.printStackTrace();
        }
        initComponents();
        java.awt.Color lightNudeBeige = new java.awt.Color(242, 230, 218);
        this.getContentPane().setBackground(lightNudeBeige);
        java.awt.Color coffeeBrown = new java.awt.Color(54, 43, 36);
        jLabel1.setForeground(coffeeBrown);
        txtname.setForeground(coffeeBrown);
        txtemail.setForeground(coffeeBrown);
        txtpassword.setForeground(coffeeBrown);
        cmbRole.setForeground(coffeeBrown);
        txtphone.setForeground(coffeeBrown);
        lbl_skills.setForeground(coffeeBrown);
        jLabel6.setForeground(coffeeBrown);
        
        java.awt.Font boldLabel = new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13);

        txtname.setFont(boldLabel);
        txtemail.setFont(boldLabel);
        txtpassword.setFont(boldLabel);
        cmbRole.setFont(boldLabel);
        lbl_skills.setFont(boldLabel);
        txtphone.setFont(boldLabel);

        // 2. Heading Style (Centered & Styled)
        jLabel1.setText("REGISTER FORM");
        jLabel1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 24));
        jLabel1.setForeground(coffeeBrown);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        // 3. Button Styling (Terracotta + White Text)
        java.awt.Color btnColor = new java.awt.Color(184, 115, 81);
        java.awt.Color textColor = java.awt.Color.WHITE;

        register_btn.setBackground(btnColor);
        register_btn.setForeground(textColor);
        register_btn.setFocusPainted(false);

        login_btn.setBackground(btnColor);
        login_btn.setForeground(textColor);
        login_btn.setFocusPainted(false);

        // 4. Input Fields (Clean White)
        name_txt.setBackground(java.awt.Color.WHITE);
        email_txt.setBackground(java.awt.Color.WHITE);
        pass_field.setBackground(java.awt.Color.WHITE);
        phone_no.setBackground(java.awt.Color.WHITE);
        txt_skills.setBackground(java.awt.Color.WHITE);
        jComboBox1.setBackground(java.awt.Color.WHITE);

        // 5. Window center mein open karne ke liye
        this.setLocationRelativeTo(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 22));
        jLabel1.setForeground(new java.awt.Color(54, 43, 36)); 
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtname = new javax.swing.JLabel();
        txtemail = new javax.swing.JLabel();
        txtpassword = new javax.swing.JLabel();
        cmbRole = new javax.swing.JLabel();
        name_txt = new javax.swing.JTextField();
        email_txt = new javax.swing.JTextField();
        pass_field = new javax.swing.JPasswordField();
        register_btn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        login_btn = new javax.swing.JButton();
        phone_no = new javax.swing.JTextField();
        txtphone = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        lbl_skills = new javax.swing.JLabel();
        txt_skills = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("REGISTER FORM");

        txtname.setText("Full Name");

        txtemail.setText("Email");

        txtpassword.setText("Password");

        cmbRole.setText("Role");

        name_txt.addActionListener(this::name_txtActionPerformed);

        email_txt.addActionListener(this::email_txtActionPerformed);

        pass_field.addActionListener(this::pass_fieldActionPerformed);

        register_btn.setText("Register");
        register_btn.addActionListener(this::register_btnActionPerformed);

        jLabel6.setText("Already have an account?");

        login_btn.setText("Login");
        login_btn.addActionListener(this::login_btnActionPerformed);

        phone_no.addActionListener(this::phone_noActionPerformed);

        txtphone.setText("phone_no");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Role", "Client", "FreeLancer" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        lbl_skills.setText("skills");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(register_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtname)
                    .addComponent(txtemail)
                    .addComponent(txtpassword)
                    .addComponent(txtphone)
                    .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_skills))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(login_btn)
                        .addContainerGap(129, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name_txt)
                            .addComponent(email_txt)
                            .addComponent(pass_field)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_skills)
                            .addComponent(phone_no))
                        .addGap(30, 30, 30))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtname))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtemail))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpassword))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbRole))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_skills, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phone_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtphone)))
                    .addComponent(lbl_skills))
                .addGap(30, 30, 30)
                .addComponent(register_btn)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(login_btn))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>                        

    private void name_txtActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void pass_fieldActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void email_txtActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void register_btnActionPerformed(java.awt.event.ActionEvent evt) {                                             
       
        String email = email_txt.getText().trim(); // txt_email

    // ===== EMAIL VALIDATION START =====
    if (email.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Email field cannot be empty!", "Validation Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (!email.contains("@") || !email.endsWith(".com")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Invalid Email Format! Must contain '@' and end with '.com'", "Validation Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return; 
    }

    int atIndex = email.indexOf("@");
    int dotIndex = email.lastIndexOf(".com");
    if (atIndex == 0 || dotIndex - atIndex <= 1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Invalid Email Structure!", "Validation Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }
        FileManagement fm = new FileManagement("users.txt");
    
        String name = name_txt.getText().trim();
        String Email = email_txt.getText().trim();
        String Password = new String(pass_field.getPassword()).trim();
        String phone = phone_no.getText().trim();
        String role = jComboBox1.getSelectedItem().toString().trim();

        if (name.isEmpty() || Email.isEmpty() || Password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all fields!");
            return;
        }

        String skills = "";

        if (role.equalsIgnoreCase("Freelancer")) {
           String inputSkills = txt_skills.getText().trim();
           skills = inputSkills.isEmpty() ? "No skills added" : inputSkills.replace(",", "|");
 
        } else if (role.equalsIgnoreCase("Client")) {
            String companyName = txt_skills.getText().trim();  // now txt_skills holds company name
            skills = companyName.isEmpty() ? "No Company" : companyName;
    }

fm.appendFile(name + "," + Email + "," + Password + "," + phone + "," + role + "," + skills);

        JOptionPane.showMessageDialog(this, "Registered Successfully!");
        name_txt.setText("");
        email_txt.setText("");
        pass_field.setText("");
        phone_no.setText("");

        try {
            txt_skills.setText("");
        } 
        catch(Exception e) {
            // Safe block if txt_skills doesn't exist on Client UI
        }
    }                                            

    private void phone_noActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        String selectedRole = jComboBox1.getSelectedItem().toString();
    
    if (selectedRole.equalsIgnoreCase("Client")) {
        
        lbl_skills.setVisible(true);        // show it for client too
        txt_skills.setVisible(true);
        lbl_skills.setText("Company Name:");
    } else {
       
        lbl_skills.setVisible(true);
        txt_skills.setVisible(true);
        lbl_skills.setText("Skills:");
    }
    }                                          

    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {                                          
        LoginForm lf = new LoginForm();
        lf.setVisible(true);
        this.dispose();
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegisterForm().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel cmbRole;
    private javax.swing.JTextField email_txt;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbl_skills;
    private javax.swing.JButton login_btn;
    private javax.swing.JTextField name_txt;
    private javax.swing.JPasswordField pass_field;
    private javax.swing.JTextField phone_no;
    private javax.swing.JButton register_btn;
    private javax.swing.JTextField txt_skills;
    private javax.swing.JLabel txtemail;
    private javax.swing.JLabel txtname;
    private javax.swing.JLabel txtpassword;
    private javax.swing.JLabel txtphone;
    // End of variables declaration                   
}
